version: "3.3"
services:
    www:
        build: .
        ports:
            - "8600:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
volumes:
    persistent:
